# Generated by Django 5.2.12 on 2026-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('staff', 'Staff Member'), ('admin', 'Administrator')], default='owner', max_length=20),
        ),
    ]
