# Generated by Django 5.2.12 on 2026-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_subscribed_profile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_credits',
            field=models.IntegerField(default=0),
        ),
    ]
