# Generated by Django 5.2.12 on 2026-03-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_message_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('owner', 'Business Owner'), ('manager', 'Manager'), ('staff', 'Staff Member')], default='owner', max_length=20),
        ),
    ]
