# Generated by Django 5.2.12 on 2026-03-17 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_complete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_tier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='trial_ends_at',
        ),
    ]
