# Generated by Django 5.2.12 on 2026-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_subscriber_encrypted_birth_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
