# Generated by Django 5.2.12 on 2026-03-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accent_color',
            field=models.CharField(blank=True, help_text='Hex code, e.g. #F4B400', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex code, e.g. #1A73E8', max_length=7),
        ),
        migrations.AddField(
            model_name='store',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
