# Generated by Django 5.2.12 on 2026-03-14 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storemember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='store',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='accent_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddConstraint(
            model_name='storemember',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='unique_store_user'),
        ),
    ]
